name: Go Test for KMS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'plugin/go.mod'

      # - name: Run tests
      #   run: go test -v ./...
